Rebase master into upgrades branch
vmware/container-service-extension-templates pull request #42
Opened 2021-06-29 20:20 UTC by andrew-ni

2021-06-30 03:40 UTC, sakthisunda approved these changes

2021-07-01 00:58 UTC, rocknes requested changes
> Reviewed 5 of 6 files at r1, 27 of 82 files at r5, 1 of 84 files at r9, 2 of 16 files at r10.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/42)* status: 35 of 162 files reviewed, 3 unresolved discussions (waiting on @andrew-ni and @ltimothy7)

___
*[template_v2.yaml, line 21 at r10](https://reviewable.io/reviews/vmware/container-service-extension-templates/42#-MdUXwhiEPcUHJWh4BmI:-MdUXwhiEPcUHJWh4BmJ:bqcekn5) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/4b3077aea9c746acf80e1d61c03fc1f173d5b221/template_v2.yaml#L21)):*
> ```YAML
>     cni_version: "2.8.1"
>     upgrade_from:
>       - "ubuntu-16.04_k8-1.20_weave-2.6.5"
> ```

Please add 1.21 template in here too.
___
*[scripts/photon-v2_k8-1.12_weave-2.3.0_rev1/cust.sh, line 24 at r10](https://reviewable.io/reviews/vmware/container-service-extension-templates/42#-MdUYGv-A4waMs4xehNL:-MdUYGv-A4waMs4xehNM:b-6jsqbb) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/4b3077aea9c746acf80e1d61c03fc1f173d5b221/scripts/photon-v2_k8-1.12_weave-2.3.0_rev1/cust.sh#L24)):*
> ```Shell
> systemctl start iptables-ports.service
> 
> # update public repository to point to packages.vmware.com
> ```

We shouldn't edit already published template scripts .. but I guess in this case this template is not referenced in template.yaml.
___
*[scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh, line 36 at r10](https://reviewable.io/reviews/vmware/container-service-extension-templates/42#-MdUZewD7tQO5pVc-F34:-MdUZewEBu_qgi4f5ZRy:b-pk6s1v) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/4b3077aea9c746acf80e1d61c03fc1f173d5b221/scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh#L36)):*
> ```Shell
> apt-get -q update -o Acquire::Retries=3 -o Acquire::http::No-Cache=True -o Acquire::http::Timeout=30 -o Acquire::https::No-Cache=True -o Acquire::https::Timeout=30 -o Acquire::ftp::Timeout=30
> apt-get -q install -y docker-ce=5:19.03.15~3-0~ubuntu-xenial
> apt-get -q install -y kubelet=1.20.6-00 kubeadm=1.20.6-00 kubectl=1.20.6-00 kubernetes-cni=0.8.7-00
> ```

This is wrong .. rev1 is supposed to have 1.20.5 .. why is it getting upped to 1.20.6 .. that should be rev 2


<!-- Sent from Reviewable.io -->

2021-07-01 01:07 UTC, rocknes reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/42#-:-MdUalQ4CeRtFUbJu0Xj:bg7igkv)* status: 35 of 162 files reviewed, 3 unresolved discussions (waiting on @andrew-ni and @ltimothy7)



<!-- Sent from Reviewable.io -->

2021-07-01 01:12 UTC, andrew-ni reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/42)* status: 35 of 162 files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[template_v2.yaml, line 21 at r10](https://reviewable.io/reviews/vmware/container-service-extension-templates/42#-MdUXwhiEPcUHJWh4BmI:-MdUbz5K0gLmyLcYbZL9:b-896fix) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/4b3077aea9c746acf80e1d61c03fc1f173d5b221/template_v2.yaml#L21)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please add 1.21 template in here too.
</blockquote></details>

Done.
___
*[scripts/photon-v2_k8-1.12_weave-2.3.0_rev1/cust.sh, line 24 at r10](https://reviewable.io/reviews/vmware/container-service-extension-templates/42#-MdUYGv-A4waMs4xehNL:-MdUbDok-5RdT2pb72sP:b-896fix) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/4b3077aea9c746acf80e1d61c03fc1f173d5b221/scripts/photon-v2_k8-1.12_weave-2.3.0_rev1/cust.sh#L24)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We shouldn't edit already published template scripts .. but I guess in this case this template is not referenced in template.yaml.
</blockquote></details>

Done.
___
*[scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh, line 36 at r10](https://reviewable.io/reviews/vmware/container-service-extension-templates/42#-MdUZewD7tQO5pVc-F34:-MdUbE66B-PzKKDsVK1j:b-896fix) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/4b3077aea9c746acf80e1d61c03fc1f173d5b221/scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh#L36)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This is wrong .. rev1 is supposed to have 1.20.5 .. why is it getting upped to 1.20.6 .. that should be rev 2
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-01 01:14 UTC, merged